BaseUrl: https://api.sample.com
TimeoutSec: 3600
ApiSpecs:
  - Name: SampleList
    Method: GET
    Path: /sample-api/v1/sample
  - Name: SampleDetail
    Method: GET
    Path: /sample-api/v1/sample/1
RequestHeaders:
  - Key: sample-header
    Value: sample-value
LogDir: logs
Scenarios:
  - Name: addUser
    LoopNum: 100
    Thread: 10
  - Name: stress
    # LoopNum: 200
    # Thread: 50
    LoopNum: 1
    Thread: 1
